let persons= [
    { name: "Francesco",
      surname: "Terrasi",
      age: 26,
      city: "Monreale",
      hobby: "football",
      favouriteFood: "pizza",
      favouriteFilm: "Iron Man",
      favouriteBook: "Harry Potter",
      petName: "Cesare",},
      { name : "Marco",
      surname:"Ruberto",
      age:30,
      city:"Tricase",
      hobby:"football",
      favouriteFood:"parmigiana",
      favouriteFilm:"Cinema Paradiso",
      favoriteBook:"One Piece",
      petName:"Scheggia"}
];
